### ISSUE TITLE
[Epic] Requirements

### ISSUE THREAD

**Issue by nelsonic** [dwyl/reading-tracker#1]
**As a person that _reads_** primarily knowledge/insight accumulation, 
***I want*** to _pace_ myself while I'm reading "popular non-fiction" 
***So that*** I can finish the books _faster_ than I currently am.

+ [ ] Every minute emit a "Tick" that informs me of the passage of time and nudges me to turn the page.
  + [ ] Count the time 
  + [ ] Emit the sound

Stretch Goals:
+ [ ] Display the Time Interval on the page.
+ [ ] Make the time/interval configurable/variable with a slider
